// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxlLRrEjI4-fkObhXkQiUpwEjKIunaAMg',
    appId: '1:788871006278:web:59d9610e56c585bc18a247',
    messagingSenderId: '788871006278',
    projectId: 'spotlessgo-96e48',
    authDomain: 'spotlessgo-96e48.firebaseapp.com',
    storageBucket: 'spotlessgo-96e48.firebasestorage.app',
    measurementId: 'G-QWXVYZ5QLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3YqPaM2sMh38UqnT3YcY9647BL2g1Mrc',
    appId: '1:788871006278:android:7adbb741581c944e18a247',
    messagingSenderId: '788871006278',
    projectId: 'spotlessgo-96e48',
    storageBucket: 'spotlessgo-96e48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy6yMqmyY4STYsDMMhRnzR-ThxFhiUiMY',
    appId: '1:788871006278:ios:e3d7676a8b127bf518a247',
    messagingSenderId: '788871006278',
    projectId: 'spotlessgo-96e48',
    storageBucket: 'spotlessgo-96e48.firebasestorage.app',
    iosClientId: '788871006278-rhudo203ugf6vpjpmkpjrf0vl100imqe.apps.googleusercontent.com',
    iosBundleId: 'com.example.spotlessgo',
  );
}
